### ISSUE TITLE
Bigtreetech SKR Mini?

### ISSUE THREAD

**Issue by eightheads** [dungjk/grbl-stm32#2]
Would this be compatible with the Bigtreetech SKR Mini control board? It is running a STM32F103RCT6 and Marlin/Smoothieware by default. If so, where would I add/change a pins file?
https://github.com/bigtreetech/BIGTREETECH-SKR-MINI-V1.1

**Comment by dineshvyas** [comment]
edit stm32_cpu_map.h in grbl folder

**Comment by Aurora4891** [comment]
@eightheads did you ever get it to work on your skr mini?

**Comment by eightheads** [comment]
> @eightheads did you ever get it to work on your skr mini?

No, I was told it wouldn't due to the way the steppers are wired on the Mini. I ended up recently using Marlin 2.0.7.1 to setup laser control and it's working great.

**Comment by Aurora4891** [comment]
> > @eightheads did you ever get it to work on your skr mini?
> 
> No, I was told it wouldn't due to the way the steppers are wired on the Mini. I ended up recently using Marlin 2.0.7.1 to setup laser control and it's working great.

Are you using octoprint or something of the like? I have a mini mill (Sieg X2D) that I have converted to 2 axis CNC have been trying to find "controller software" to use on a Raspberry Pi but a lot of them seem to not play nice with Marlin.

**Comment by eightheads** [comment]
There is a GRBL plugin for Octoprint that worked decent last I played with
it. I'm running the laser from sd card currently.
